version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.3.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer-config/base.json
  build-base:
    docker:
      - image: hashicorp/packer:1.3.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: "Setup AWS environment variables"
          command: |
            echo "aws_access_key: $aws_access_key"
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: |
            echo "aws_access_key: $aws_access_key"
            packer build ./packer-config/base.json
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-base.json
      - store_artifacts:
          path: manifest-base.json
workflows:
  version: 2
  validate-and-build:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
