version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.3.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer-config/base.json
  build-base:
    docker:
      - image: hashicorp/packer:1.3.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Build base
          command: packer build ./packer-config/base.json
          no_output_timeout: 30m
workflows:
  version: 2
  validate-and-build:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
